# Generated by Django 5.0.6 on 2026-05-18 16:30

from django.db import migrations, models
from django.db.models import F


def populate_current_points(apps, schema_editor):
    EduquestUser = apps.get_model("api", "EduquestUser")
    EduquestUser.objects.all().update(current_points=F("total_points"))


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_usercosmetics"),
    ]

    operations = [
        migrations.AddField(
            model_name="eduquestuser",
            name="current_points",
            field=models.FloatField(default=0),
        ),
        migrations.RunPython(populate_current_points, reverse_code=migrations.RunPython.noop),
    ]
