# Generated by Django 5.0.6 on 2026-05-18 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_usercosmetics"),
    ]

    operations = [
        migrations.AddField(
            model_name="eduquestuser",
            name="current_points",
            field=models.FloatField(default=0),
        ),
    ]
