# Generated by Django 5.0.6 on 2026-05-18 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_eduquestuser_current_points"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usercosmetics",
            name="displayed_badges",
            field=models.ManyToManyField(blank=True, to="api.badge"),
        ),
        migrations.AlterField(
            model_name="usercosmetics",
            name="profile_background",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="usercosmetics",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.CreateModel(
            name="Cosmetic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Picture", "Picture"),
                            ("Border", "Border"),
                            ("Banner", "Banner"),
                        ],
                        max_length=50,
                    ),
                ),
                ("cost", models.FloatField(default=0)),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.image",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="usercosmetics",
            name="banner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="usercosmetics_banner",
                to="api.cosmetic",
            ),
        ),
        migrations.AlterField(
            model_name="usercosmetics",
            name="profile_border",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="usercosmetics_profile_border",
                to="api.cosmetic",
            ),
        ),
        migrations.AlterField(
            model_name="usercosmetics",
            name="profile_picture",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="usercosmetics_profile_picture",
                to="api.cosmetic",
            ),
        ),
    ]
