# Generated by Django 5.0.6 on 2026-05-30 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_cosmetic"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userdailycheckin",
            options={},
        ),
        migrations.AddField(
            model_name="usercosmetics",
            name="owns",
            field=models.ManyToManyField(blank=True, to="api.cosmetic"),
        ),
    ]
