# Generated by Django 5.0.6 on 2026-06-02 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0019_alter_userdailycheckin_options_usercosmetics_owns"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usercosmetics",
            name="displayed_badges",
        ),
        migrations.CreateModel(
            name="UserCosmeticBadge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("display_order", models.PositiveIntegerField()),
                (
                    "badge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.badge"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["display_order"],
                "unique_together": {("user", "badge")},
            },
        ),
    ]
