# Generated by Django 5.0.6 on 2026-06-17 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_usercosmetics_about_me_and_add_test_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnstructuredAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='unstructuredanswer', to='api.question')),
            ],
        ),
        migrations.CreateModel(
            name='UserShortAnswerAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('hint_used', models.BooleanField(default=False)),
                ('score_achieved', models.FloatField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_short_answer_attempts', to='api.question')),
                ('unstructuredanswer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.unstructuredanswer')),
                ('user_quest_attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='short_answer_attempts', to='api.userquestattempt')),
            ],
        ),
    ]
