# Generated by Django 5.0.6 on 2026-06-21 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_unstructuredanswer_usershortanswerattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='cosmetic',
            name='purchaseable',
            field=models.BooleanField(default=True),
        ),
    ]
